# fly.toml app configuration file generated for silent-glitter-5987-exit-node on 2025-03-27T13:06:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'silent-glitter-5987-exit-node'
primary_region = 'lax'
swap_size_mb = 512

[build]

[env]
  HEADSCALE_URL = 'https://silent-glitter-5987.fly.dev'

[processes]
  app = '/bin/sh /app/start_tailscale.sh'

[[mounts]]
  source = 'data'
  destination = '/var/lib/tailscale'
  initial_size = '1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[restart]]
  policy = 'always'

[[vm]]
  size = 'performance-1x'
